-- ============================================================
-- OKAYLIGHT LED 参数筛选器 - Supabase 数据库初始化脚本
-- ============================================================
-- 项目：OKAYLIGHT LED 参数筛选器
-- 说明：创建分类表、产品表，启用 RLS 策略，并插入初始数据
-- 日期：2026-07-25
-- ============================================================

-- ------------------------------------------------------------
-- 1. 创建表结构
-- ------------------------------------------------------------

-- 分类表
CREATE TABLE IF NOT EXISTS categories (
    id TEXT PRIMARY KEY,
    name TEXT,
    sort_order INT,
    config JSONB
);

-- 产品表
CREATE TABLE IF NOT EXISTS products (
    id BIGSERIAL PRIMARY KEY,
    category TEXT REFERENCES categories(id),
    kind TEXT,
    model TEXT,
    manufacturer TEXT,
    spec_data JSONB,
    price TEXT,
    datasheet_url TEXT,
    image_url TEXT,
    remarks TEXT,
    sort_order INT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- ------------------------------------------------------------
-- 2. 创建索引
-- ------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_products_model ON products(model);

-- ------------------------------------------------------------
-- 3. 启用行级安全策略 (RLS)
-- ------------------------------------------------------------

ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- 4. RLS 策略（公开读写）
-- ------------------------------------------------------------

-- 分类表：允许公开读写
DROP POLICY IF EXISTS "Public read access on categories" ON categories;
CREATE POLICY "Public read access on categories"
    ON categories FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Public write access on categories" ON categories;
CREATE POLICY "Public write access on categories"
    ON categories FOR ALL
    USING (true)
    WITH CHECK (true);

-- 产品表：允许公开读写
DROP POLICY IF EXISTS "Public read access on products" ON products;
CREATE POLICY "Public read access on products"
    ON products FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Public write access on products" ON products;
CREATE POLICY "Public write access on products"
    ON products FOR ALL
    USING (true)
    WITH CHECK (true);

-- ------------------------------------------------------------
-- 5. 插入分类数据（16 个 LED 分类）
-- ------------------------------------------------------------

INSERT INTO categories (id, name, sort_order, config) VALUES
('led', '发光二极管/LED', 1, '{"filters":[{"key":"package_spec","name":"封装/规格","options":["0603","0805","1206","2835","3528","5050","3mm","5mm"]},{"key":"diode_config","name":"二极管配置","options":["单芯片","3芯片共阳","3芯片共阴"]},{"key":"emission_color","name":"发光颜色","options":["白光","暖白光","冷白光","红光","绿光","蓝光","黄光"]},{"key":"forward_current","name":"正向电流","options":["20mA","60mA"]},{"key":"forward_voltage","name":"正向压降(Vf)","options":["2.0V","2.1V","2.2V","3.0V","3.2V"]},{"key":"power","name":"功率","options":["0.04W","0.042W","0.044W","0.06W","0.064W","0.12W","0.18W","0.2W"]},{"key":"wavelength","name":"波长","options":["-","470nm","525nm","590nm","620nm"]},{"key":"color_temp","name":"色温","options":["-","3000K","5000K","6000K","6500K"]},{"key":"luminous_intensity","name":"发光强度","options":["1500mcd","1800mcd","2000mcd","2500mcd","3000mcd","6000mcd","8000mcd"]},{"key":"viewing_angle","name":"发光角度","options":["15°","30°","120°"]},{"key":"lens_color","name":"透镜颜色","options":["乳白","红色","蓝色","绿色","黄色"]},{"key":"tape_type","name":"载带方式","options":["编带","盒装"]},{"key":"base_type","name":"灯头类型","options":["贴片","直插"]},{"key":"operating_temp","name":"工作温度","options":["-40℃~85℃","-40℃~100℃"]}]}'),
('uv_led', '紫外线LED(UVLED)', 2, '{"filters":[{"key":"package_spec","name":"封装/规格","options":["0603","3535","6868"]},{"key":"peak_wavelength","name":"峰值波长","options":["365nm","385nm","395nm","405nm"]},{"key":"power_dissipation","name":"耗散功率(Pd)","options":["0.12W","1.0W","3.0W"]},{"key":"forward_current","name":"正向电流","options":["20mA","350mA","700mA"]},{"key":"forward_voltage","name":"正向压降(Vf)","options":["3.2V","3.4V","3.6V"]},{"key":"luminous_intensity","name":"发光强度","options":["-","300mcd"]},{"key":"fwhm","name":"半波宽","options":["12nm","13nm","15nm"]},{"key":"esd_rating","name":"抗静电能力","options":["HBM 1000V","HBM 2000V","HBM 4000V"]},{"key":"reverse_voltage","name":"直流反向耐压(Vr)","options":["5V"]},{"key":"reverse_current","name":"反向电流(Ir)","options":["5uA","10uA"]},{"key":"operating_temp","name":"工作温度","options":["-40℃~85℃","-40℃~100℃"]},{"key":"radiant_power","name":"辐射功率","options":["15mW","500mW","600mW","700mW","1800mW"]}]}'),
('cob', 'COB光源', 3, '{"filters":[{"key":"package_spec","name":"封装/规格","options":["COB-1616","COB-1919","COB-2424","COB-2828","COB-4040"]},{"key":"emission_color","name":"发光颜色","options":["白光","暖白光","冷白光","红光"]},{"key":"forward_current","name":"正向电流","options":["150mA","250mA","350mA","600mA","1000mA"]},{"key":"forward_voltage","name":"正向压降(Vf)","options":["8.5V","33V","40V","50V"]},{"key":"power","name":"功率","options":["3W","5W","10W","30W","50W"]},{"key":"wavelength","name":"波长","options":["-","630nm"]},{"key":"color_temp","name":"色温","options":["-","3000K","5000K","6500K"]},{"key":"cri","name":"CRI显色指数","options":["-","80","90"]},{"key":"luminous_flux","name":"光通量(25℃)","options":["120lm","450lm","900lm","3000lm","5000lm"]},{"key":"viewing_angle","name":"发光角度","options":["120°"]},{"key":"operating_temp","name":"工作温度","options":["-40℃~85℃","-40℃~105℃"]}]}'),
('ir_emitter', '红外发射管', 4, '{"filters":[{"key":"package_spec","name":"封装/规格","options":["0603","3mm","5mm","3535"]},{"key":"forward_current","name":"正向电流","options":["20mA","100mA"]},{"key":"forward_voltage","name":"正向压降(Vf)","options":["1.2V","1.3V","1.4V"]},{"key":"wavelength","name":"波长","options":["850nm","940nm"]},{"key":"radiant_intensity","name":"辐射强度(Ie)","options":["5mW/sr","10mW/sr","15mW/sr","25mW/sr","60mW/sr"]},{"key":"viewing_angle","name":"视角","options":["20°","30°","40°","60°"]},{"key":"fwhm","name":"半波宽","options":["45nm"]},{"key":"power_dissipation","name":"耗散功率(Pd)","options":["0.075W","0.1W","0.5W"]},{"key":"reverse_voltage","name":"直流反向耐压(Vr)","options":["5V"]},{"key":"operating_temp","name":"工作温度","options":["-40℃~85℃","-40℃~100℃"]}]}'),
('phototransistor', '光电晶体管', 5, '{"filters":[{"key":"package_spec","name":"封装/规格","options":["0603","3mm","5mm","1206"]},{"key":"transistor_type","name":"晶体管类型","options":["NPN","达林顿"]},{"key":"peak_wavelength","name":"峰值波长","options":["940nm"]},{"key":"vceo","name":"集射极击穿电压(Vceo)","options":["30V","50V"]},{"key":"collector_current","name":"集电极电流(Ic)","options":["20mA","50mA"]},{"key":"viewing_angle","name":"视角","options":["20°","30°","40°"]},{"key":"vce_sat","name":"集射极饱和电压(VCE(sat))","options":["0.4V","1.0V"]},{"key":"power_dissipation","name":"耗散功率(Pd)","options":["0.075W","0.1W","0.15W"]},{"key":"dark_current","name":"暗电流","options":["100nA"]},{"key":"operating_temp","name":"工作温度","options":["-40℃~85℃"]}]}'),
('irm', '红外遥控接收头(IRM)', 6, '{"filters":[{"key":"package_spec","name":"封装/规格","options":["IRM-0038","IRM-1838","IRM-3638","IRM-3838-SMD","IRM-5638"]},{"key":"receive_distance","name":"接收距离","options":["10m","15m","18m","20m"]},{"key":"center_frequency","name":"中心频率","options":["38kHz"]},{"key":"receive_angle","name":"接收角度","options":["±35°","±45°"]},{"key":"working_voltage","name":"工作电压","options":["2.7-5.5V"]},{"key":"working_current","name":"工作电流","options":["0.5mA","0.6mA","0.8mA"]},{"key":"power_dissipation","name":"耗散功率(Pd)","options":["0.03W","0.04W","0.05W"]},{"key":"operating_temp","name":"工作温度","options":["-25℃~85℃"]}]}'),
('photodiode', '光电二极管', 7, '{"filters":[{"key":"package_spec","name":"封装/规格","options":["0603","3mm","5mm","1206"]},{"key":"peak_wavelength","name":"峰值波长","options":["850nm","940nm"]},{"key":"spectral_range","name":"频谱范围","options":["400-1100nm"]},{"key":"receive_angle","name":"接收角度","options":["20°","30°","40°"]},{"key":"reverse_voltage","name":"直流反向耐压(Vr)","options":["30V"]},{"key":"power_dissipation","name":"耗散功率(Pd)","options":["0.075W","0.1W"]},{"key":"dark_current","name":"暗电流","options":["30nA"]},{"key":"operating_temp","name":"工作温度","options":["-40℃~85℃"]}]}'),
('laser_diode', '激光二极管', 8, '{"filters":[{"key":"package_spec","name":"封装/规格","options":["3.3mm","TO-18","TO-56"]},{"key":"dominant_wavelength","name":"主波长","options":["520nm","650nm","808nm","445nm"]},{"key":"conversion_efficiency","name":"转换效率","options":["20%","25%","28%","30%","40%"]},{"key":"threshold_current","name":"阈值电流","options":["25mA","35mA","60mA","70mA","120mA"]},{"key":"esd_rating","name":"抗静电能力","options":["HBM 500V"]},{"key":"working_voltage","name":"工作电压","options":["1.8V","2.2V","4.5V"]},{"key":"working_current","name":"工作电流","options":["30mA","40mA","140mA","250mA","350mA"]},{"key":"emission_color","name":"发光颜色","options":["红光","绿光","蓝光","红外"]},{"key":"horizontal_divergence","name":"水平散射角度","options":["6°","8°"]},{"key":"vertical_divergence","name":"垂直散射角度","options":["30°","35°"]},{"key":"output_power","name":"输出光功率","options":["1mW","5mW","50mW","200mW","1000mW"]},{"key":"slope_efficiency","name":"斜率效率","options":["0.2mW/mA","0.3mW/mA","0.5mW/mA","0.6mW/mA","1.0mW/mA"]},{"key":"operating_temp","name":"工作温度","options":["-10℃~60℃"]}]}'),
('rgb_led', 'RGB LED', 9, '{"filters":[{"key":"package_spec","name":"封装/规格","options":["1206","3528","5050","5mm"]},{"key":"diode_config","name":"二极管配置","options":["3芯片共阳","3芯片共阴"]},{"key":"esd_rating","name":"抗静电能力","options":["HBM 2000V"]},{"key":"viewing_angle","name":"发光角度","options":["30°","120°"]},{"key":"dominant_wavelength_g","name":"主波长-绿","options":["525nm","530nm"]},{"key":"dominant_wavelength_b","name":"主波长-蓝","options":["460nm","470nm"]},{"key":"dominant_wavelength_r","name":"主波长-红","options":["620nm","625nm"]},{"key":"base_type","name":"灯头类型","options":["贴片","直插"]},{"key":"lens_color","name":"透镜颜色","options":["乳白","透明"]},{"key":"tape_type","name":"载带方式","options":["编带","盒装"]},{"key":"peak_wavelength_g","name":"峰值波长-绿","options":["515nm","520nm"]},{"key":"peak_wavelength_b","name":"峰值波长-蓝","options":["455nm","465nm"]},{"key":"peak_wavelength_r","name":"峰值波长-红","options":["625nm","630nm"]},{"key":"luminous_intensity_g","name":"发光强度-绿","options":["1500mcd","2000mcd","3000mcd","3500mcd","4000mcd"]},{"key":"luminous_intensity_b","name":"发光强度-蓝","options":["1200mcd","1800mcd","2500mcd","2800mcd","3000mcd"]},{"key":"luminous_intensity_r","name":"发光强度-红","options":["1000mcd","1500mcd","2000mcd","2200mcd","2500mcd"]},{"key":"forward_voltage_g","name":"正向压降(Vf)-绿","options":["3.0V","3.2V"]},{"key":"forward_voltage_b","name":"正向压降(Vf)-蓝","options":["3.0V","3.2V"]},{"key":"forward_voltage_r","name":"正向压降(Vf)-红","options":["2.0V"]},{"key":"forward_current_g","name":"正向电流-绿","options":["20mA"]},{"key":"forward_current_b","name":"正向电流-蓝","options":["20mA"]},{"key":"forward_current_r","name":"正向电流-红","options":["20mA"]},{"key":"power_r","name":"功率-红","options":["0.04W"]},{"key":"power_g","name":"功率-绿","options":["0.06W","0.064W"]},{"key":"power_b","name":"功率-蓝","options":["0.06W","0.064W"]},{"key":"operating_temp","name":"工作温度","options":["-40℃~85℃"]}]}'),
('rgb_led_ic', 'RGB LED(内置IC)', 10, '{"filters":[{"key":"package_spec","name":"封装/规格","options":["3528","5050"]},{"key":"esd_rating","name":"抗静电能力","options":["HBM 2000V"]},{"key":"viewing_angle","name":"发光角度","options":["120°"]},{"key":"working_voltage","name":"工作电压","options":["3.3-5V","5V"]},{"key":"static_current","name":"静态电流","options":["0.4mA","0.6mA","0.8mA"]},{"key":"pwm_frequency","name":"PWM频率","options":["400Hz","1.2kHz"]},{"key":"data_rate","name":"数据速率","options":["800Kbps"]},{"key":"dominant_wavelength_g","name":"主波长-绿","options":["525nm"]},{"key":"dominant_wavelength_b","name":"主波长-蓝","options":["470nm"]},{"key":"dominant_wavelength_r","name":"主波长-红","options":["620nm"]},{"key":"base_type","name":"灯头类型","options":["贴片"]},{"key":"lens_color","name":"透镜颜色","options":["乳白"]},{"key":"tape_type","name":"载带方式","options":["编带"]},{"key":"peak_wavelength_g","name":"峰值波长-绿","options":["515nm"]},{"key":"peak_wavelength_b","name":"峰值波长-蓝","options":["465nm"]},{"key":"peak_wavelength_r","name":"峰值波长-红","options":["625nm"]},{"key":"luminous_intensity_g","name":"发光强度-绿","options":["2000mcd","3000mcd","3500mcd"]},{"key":"luminous_intensity_b","name":"发光强度-蓝","options":["1800mcd","2500mcd","2800mcd","3000mcd"]},{"key":"luminous_intensity_r","name":"发光强度-红","options":["1500mcd","2000mcd","2200mcd","2500mcd"]},{"key":"propagation_delay","name":"传输延迟","options":["300ns"]},{"key":"rise_time","name":"上升时间","options":["300ns"]},{"key":"fall_time","name":"下降时间","options":["300ns"]},{"key":"operating_temp","name":"工作温度","options":["-40℃~85℃"]}]}'),
('slot_photo_switch', '槽型光电开关(光电晶体管输出)', 11, '{"filters":[{"key":"package_spec","name":"封装/规格"},{"key":"slot_width","name":"槽宽"},{"key":"slit_width","name":"缝隙宽"},{"key":"forward_voltage","name":"正向压降(Vf)"},{"key":"peak_wavelength","name":"峰值波长"},{"key":"dark_current","name":"暗电流"},{"key":"load_voltage","name":"负载电压"},{"key":"load_current","name":"负载电流"},{"key":"rise_time","name":"上升时间(tr)"},{"key":"fall_time","name":"下降时间(tf)"},{"key":"pin_pitch","name":"脚间距"},{"key":"operating_temp","name":"工作温度"}]}'),
('reflective_photo_switch', '反射式光电开关', 12, '{"filters":[{"key":"package_spec","name":"封装/规格"},{"key":"sensing_distance","name":"感应距离"},{"key":"receiver_type","name":"接收管类型"},{"key":"collector_current","name":"集电极电流(Ic)"},{"key":"vceo","name":"集射极击穿电压(Vceo)"},{"key":"vce_sat","name":"集射极饱和电压(Vce(sat))"},{"key":"wavelength","name":"波长"},{"key":"forward_voltage","name":"正向压降(Vf)"},{"key":"forward_current","name":"正向电流(If)"},{"key":"reverse_voltage","name":"直流反向耐压(Vr)"},{"key":"rise_time","name":"上升时间"},{"key":"fall_time","name":"下降时间"},{"key":"power_dissipation","name":"功耗(Pd)"},{"key":"operating_temp","name":"工作温度"}]}'),
('led_driver', 'LED驱动', 13, '{"filters":[{"key":"package_spec","name":"封装/规格"},{"key":"driver_type","name":"类型"},{"key":"topology","name":"拓扑结构"},{"key":"channel_count","name":"通道数"},{"key":"working_voltage_dc","name":"工作电压(DC)"},{"key":"working_voltage_ac","name":"工作电压(AC)"},{"key":"switching_frequency","name":"开关频率"},{"key":"switch_type","name":"开关管(内置/外置)"},{"key":"output_voltage","name":"输出电压"},{"key":"output_current","name":"输出电流"},{"key":"current_accuracy","name":"恒流精度"},{"key":"dimming","name":"调光"},{"key":"features","name":"功能特性"},{"key":"operating_temp","name":"工作温度"}]}'),
('led_display', 'LED数码管', 14, '{"filters":[{"key":"package_spec","name":"封装/规格"},{"key":"digit_count","name":"数码管位数"},{"key":"char_size","name":"字符尺寸(英寸)"},{"key":"display_type","name":"显示类型"},{"key":"led_polarity","name":"LED极性"},{"key":"emission_color","name":"发光颜色"},{"key":"luminous_intensity","name":"发光强度"},{"key":"power_dissipation","name":"耗散功率(Pd)"},{"key":"forward_voltage","name":"正向压降"},{"key":"operating_temp","name":"工作温度"}]}'),
('led_protection', 'LED保护', 15, '{"filters":[{"key":"package_spec","name":"封装/规格"},{"key":"trigger_voltage","name":"触发电压"},{"key":"leakage_current","name":"漏电流"},{"key":"hold_current","name":"保持电流(Ih)"},{"key":"on_state_voltage","name":"通态电压(Vt)"},{"key":"on_state_current","name":"通态电流(It)"},{"key":"features","name":"功能特性"},{"key":"operating_temp","name":"工作温度"}]}'),
('tvs_esd', '静电和浪涌保护(TVS/ESD)', 16, '{"filters":[{"key":"package_spec","name":"封装/规格"},{"key":"device_type","name":"类型"},{"key":"channel_count","name":"通道数"},{"key":"polarity","name":"极性"},{"key":"vrwm","name":"反向截止电压(Vrwm)"},{"key":"vbr","name":"击穿电压(VBR)"},{"key":"reverse_current","name":"反向电流(Ir)"},{"key":"ipp","name":"峰值脉冲电流(Ipp)"},{"key":"clamp_voltage","name":"钳位电压"},{"key":"ppp","name":"峰值脉冲功率(Ppp)"},{"key":"cj","name":"Cj-结电容"},{"key":"protection_level","name":"防护等级"},{"key":"operating_temp","name":"工作温度"}]}');

-- ------------------------------------------------------------
-- 6. 插入示例产品数据
-- ------------------------------------------------------------

-- 6.1 发光二极管/LED 产品
INSERT INTO products (category, kind, model, manufacturer, spec_data, price, datasheet_url, image_url, remarks, sort_order) VALUES
('led', 'default', 'OKL-0603-W', 'OKAYLIGHT', '{"package_spec":"0603","diode_config":"单芯片","emission_color":"白光","forward_current":"20mA","forward_voltage":"3.0V","power":"0.06W","wavelength":"-","color_temp":"6000K","luminous_intensity":"2000mcd","viewing_angle":"120°","lens_color":"乳白","tape_type":"编带","base_type":"贴片","operating_temp":"-40℃~85℃"}', '0.08', '', 'https://picsum.photos/seed/OKL0603W/300/300', '', 1),
('led', 'default', 'OKL-0805-R', 'OKAYLIGHT', '{"package_spec":"0805","diode_config":"单芯片","emission_color":"红光","forward_current":"20mA","forward_voltage":"2.0V","power":"0.04W","wavelength":"620nm","color_temp":"-","luminous_intensity":"1500mcd","viewing_angle":"120°","lens_color":"红色","tape_type":"编带","base_type":"贴片","operating_temp":"-40℃~85℃"}', '0.06', '', 'https://picsum.photos/seed/OKL0805R/300/300', '', 2),
('led', 'default', 'OKL-1206-B', 'OKAYLIGHT', '{"package_spec":"1206","diode_config":"单芯片","emission_color":"蓝光","forward_current":"20mA","forward_voltage":"3.2V","power":"0.064W","wavelength":"470nm","color_temp":"-","luminous_intensity":"2500mcd","viewing_angle":"120°","lens_color":"蓝色","tape_type":"编带","base_type":"贴片","operating_temp":"-40℃~85℃"}', '0.10', '', 'https://picsum.photos/seed/OKL1206B/300/300', '', 3),
('led', 'default', 'OKL-3528-WW', 'OKAYLIGHT', '{"package_spec":"3528","diode_config":"单芯片","emission_color":"暖白光","forward_current":"20mA","forward_voltage":"3.0V","power":"0.06W","wavelength":"-","color_temp":"3000K","luminous_intensity":"1800mcd","viewing_angle":"120°","lens_color":"乳白","tape_type":"编带","base_type":"贴片","operating_temp":"-40℃~85℃"}', '0.09', '', 'https://picsum.photos/seed/OKL3528WW/300/300', '', 4),
('led', 'default', 'OKL-5050-W', 'OKAYLIGHT', '{"package_spec":"5050","diode_config":"单芯片","emission_color":"白光","forward_current":"60mA","forward_voltage":"3.2V","power":"0.2W","wavelength":"-","color_temp":"6500K","luminous_intensity":"8000mcd","viewing_angle":"120°","lens_color":"乳白","tape_type":"编带","base_type":"贴片","operating_temp":"-40℃~85℃"}', '0.15', '', 'https://picsum.photos/seed/OKL5050W/300/300', '', 5),
('led', 'default', 'OKL-3MM-G-DIP', 'OKAYLIGHT', '{"package_spec":"3mm","diode_config":"单芯片","emission_color":"绿光","forward_current":"20mA","forward_voltage":"2.2V","power":"0.044W","wavelength":"525nm","color_temp":"-","luminous_intensity":"3000mcd","viewing_angle":"30°","lens_color":"绿色","tape_type":"盒装","base_type":"直插","operating_temp":"-40℃~85℃"}', '0.05', '', 'https://picsum.photos/seed/OKL3MMGDIP/300/300', '', 6),
('led', 'default', 'OKL-5MM-Y-DIP', 'OKAYLIGHT', '{"package_spec":"5mm","diode_config":"单芯片","emission_color":"黄光","forward_current":"20mA","forward_voltage":"2.1V","power":"0.042W","wavelength":"590nm","color_temp":"-","luminous_intensity":"2000mcd","viewing_angle":"15°","lens_color":"黄色","tape_type":"盒装","base_type":"直插","operating_temp":"-40℃~85℃"}', '0.05', '', 'https://picsum.photos/seed/OKL5MMYDIP/300/300', '', 7),
('led', 'default', 'OKL-2835-W', 'OKAYLIGHT', '{"package_spec":"2835","diode_config":"单芯片","emission_color":"白光","forward_current":"60mA","forward_voltage":"3.0V","power":"0.18W","wavelength":"-","color_temp":"5000K","luminous_intensity":"6000mcd","viewing_angle":"120°","lens_color":"乳白","tape_type":"编带","base_type":"贴片","operating_temp":"-40℃~100℃"}', '0.12', '', 'https://picsum.photos/seed/OKL2835W/300/300', '', 8);

-- 6.2 紫外线LED(UVLED) 产品
INSERT INTO products (category, kind, model, manufacturer, spec_data, price, datasheet_url, image_url, remarks, sort_order) VALUES
('uv_led', 'default', 'OKL-UV-3535-365', 'OKAYLIGHT', '{"package_spec":"3535","peak_wavelength":"365nm","power_dissipation":"1.0W","forward_current":"350mA","forward_voltage":"3.4V","luminous_intensity":"-","fwhm":"12nm","esd_rating":"HBM 2000V","reverse_voltage":"5V","reverse_current":"10uA","operating_temp":"-40℃~85℃","radiant_power":"500mW"}', '1.85', '', 'https://picsum.photos/seed/OKLUV3535365/300/300', '', 1),
('uv_led', 'default', 'OKL-UV-3535-385', 'OKAYLIGHT', '{"package_spec":"3535","peak_wavelength":"385nm","power_dissipation":"1.0W","forward_current":"350mA","forward_voltage":"3.4V","luminous_intensity":"-","fwhm":"12nm","esd_rating":"HBM 2000V","reverse_voltage":"5V","reverse_current":"10uA","operating_temp":"-40℃~85℃","radiant_power":"600mW"}', '1.65', '', 'https://picsum.photos/seed/OKLUV3535385/300/300', '', 2),
('uv_led', 'default', 'OKL-UV-3535-395', 'OKAYLIGHT', '{"package_spec":"3535","peak_wavelength":"395nm","power_dissipation":"1.0W","forward_current":"350mA","forward_voltage":"3.4V","luminous_intensity":"-","fwhm":"13nm","esd_rating":"HBM 2000V","reverse_voltage":"5V","reverse_current":"10uA","operating_temp":"-40℃~85℃","radiant_power":"700mW"}', '1.45', '', 'https://picsum.photos/seed/OKLUV3535395/300/300', '', 3),
('uv_led', 'default', 'OKL-UV-0603-405', 'OKAYLIGHT', '{"package_spec":"0603","peak_wavelength":"405nm","power_dissipation":"0.12W","forward_current":"20mA","forward_voltage":"3.2V","luminous_intensity":"300mcd","fwhm":"15nm","esd_rating":"HBM 1000V","reverse_voltage":"5V","reverse_current":"5uA","operating_temp":"-40℃~85℃","radiant_power":"15mW"}', '0.35', '', 'https://picsum.photos/seed/OKLUV0603405/300/300', '', 4),
('uv_led', 'default', 'OKL-UV-6868-395', 'OKAYLIGHT', '{"package_spec":"6868","peak_wavelength":"395nm","power_dissipation":"3.0W","forward_current":"700mA","forward_voltage":"3.6V","luminous_intensity":"-","fwhm":"13nm","esd_rating":"HBM 4000V","reverse_voltage":"5V","reverse_current":"10uA","operating_temp":"-40℃~100℃","radiant_power":"1800mW"}', '3.85', '', 'https://picsum.photos/seed/OKLUV6868395/300/300', '', 5);

-- 6.3 COB光源 产品
INSERT INTO products (category, kind, model, manufacturer, spec_data, price, datasheet_url, image_url, remarks, sort_order) VALUES
('cob', 'default', 'OKL-COB-5W-WW', 'OKAYLIGHT', '{"package_spec":"COB-1919","emission_color":"暖白光","forward_current":"150mA","forward_voltage":"33V","power":"5W","wavelength":"-","color_temp":"3000K","cri":"80","luminous_flux":"450lm","viewing_angle":"120°","operating_temp":"-40℃~85℃"}', '1.25', '', 'https://picsum.photos/seed/OKLCOB5WWW/300/300', '', 1),
('cob', 'default', 'OKL-COB-10W-W', 'OKAYLIGHT', '{"package_spec":"COB-2424","emission_color":"白光","forward_current":"250mA","forward_voltage":"40V","power":"10W","wavelength":"-","color_temp":"5000K","cri":"80","luminous_flux":"900lm","viewing_angle":"120°","operating_temp":"-40℃~85℃"}', '2.15', '', 'https://picsum.photos/seed/OKLCOB10WW/300/300', '', 2),
('cob', 'default', 'OKL-COB-30W-WW', 'OKAYLIGHT', '{"package_spec":"COB-2828","emission_color":"暖白光","forward_current":"600mA","forward_voltage":"50V","power":"30W","wavelength":"-","color_temp":"3000K","cri":"90","luminous_flux":"3000lm","viewing_angle":"120°","operating_temp":"-40℃~105℃"}', '4.85', '', 'https://picsum.photos/seed/OKLCOB30WWW/300/300', '', 3),
('cob', 'default', 'OKL-COB-50W-CW', 'OKAYLIGHT', '{"package_spec":"COB-4040","emission_color":"冷白光","forward_current":"1000mA","forward_voltage":"50V","power":"50W","wavelength":"-","color_temp":"6500K","cri":"80","luminous_flux":"5000lm","viewing_angle":"120°","operating_temp":"-40℃~105℃"}', '7.85', '', 'https://picsum.photos/seed/OKLCOB50WCW/300/300', '', 4),
('cob', 'default', 'OKL-COB-3W-R', 'OKAYLIGHT', '{"package_spec":"COB-1616","emission_color":"红光","forward_current":"350mA","forward_voltage":"8.5V","power":"3W","wavelength":"630nm","color_temp":"-","cri":"-","luminous_flux":"120lm","viewing_angle":"120°","operating_temp":"-40℃~85℃"}', '0.85', '', 'https://picsum.photos/seed/OKLCOB3WR/300/300', '', 5);

-- 6.4 红外发射管 产品
INSERT INTO products (category, kind, model, manufacturer, spec_data, price, datasheet_url, image_url, remarks, sort_order) VALUES
('ir_emitter', 'default', 'OKL-IR-5MM-940', 'OKAYLIGHT', '{"package_spec":"5mm","forward_current":"20mA","forward_voltage":"1.2V","wavelength":"940nm","radiant_intensity":"15mW/sr","viewing_angle":"30°","fwhm":"45nm","power_dissipation":"0.1W","reverse_voltage":"5V","operating_temp":"-40℃~85℃"}', '0.08', '', 'https://picsum.photos/seed/OKLIR5MM940/300/300', '', 1),
('ir_emitter', 'default', 'OKL-IR-5MM-850', 'OKAYLIGHT', '{"package_spec":"5mm","forward_current":"20mA","forward_voltage":"1.3V","wavelength":"850nm","radiant_intensity":"25mW/sr","viewing_angle":"30°","fwhm":"45nm","power_dissipation":"0.1W","reverse_voltage":"5V","operating_temp":"-40℃~85℃"}', '0.10', '', 'https://picsum.photos/seed/OKLIR5MM850/300/300', '', 2),
('ir_emitter', 'default', 'OKL-IR-0603-940', 'OKAYLIGHT', '{"package_spec":"0603","forward_current":"20mA","forward_voltage":"1.2V","wavelength":"940nm","radiant_intensity":"5mW/sr","viewing_angle":"40°","fwhm":"45nm","power_dissipation":"0.075W","reverse_voltage":"5V","operating_temp":"-40℃~85℃"}', '0.06', '', 'https://picsum.photos/seed/OKLIR0603940/300/300', '', 3),
('ir_emitter', 'default', 'OKL-IR-3535-940', 'OKAYLIGHT', '{"package_spec":"3535","forward_current":"100mA","forward_voltage":"1.4V","wavelength":"940nm","radiant_intensity":"60mW/sr","viewing_angle":"60°","fwhm":"45nm","power_dissipation":"0.5W","reverse_voltage":"5V","operating_temp":"-40℃~100℃"}', '0.28', '', 'https://picsum.photos/seed/OKLIR3535940/300/300', '', 4),
('ir_emitter', 'default', 'OKL-IR-3MM-940', 'OKAYLIGHT', '{"package_spec":"3mm","forward_current":"20mA","forward_voltage":"1.2V","wavelength":"940nm","radiant_intensity":"10mW/sr","viewing_angle":"20°","fwhm":"45nm","power_dissipation":"0.1W","reverse_voltage":"5V","operating_temp":"-40℃~85℃"}', '0.07', '', 'https://picsum.photos/seed/OKLIR3MM940/300/300', '', 5);

-- 6.5 光电晶体管 产品
INSERT INTO products (category, kind, model, manufacturer, spec_data, price, datasheet_url, image_url, remarks, sort_order) VALUES
('phototransistor', 'default', 'OKL-PT-3MM-NPN', 'OKAYLIGHT', '{"package_spec":"3mm","transistor_type":"NPN","peak_wavelength":"940nm","vceo":"30V","collector_current":"20mA","viewing_angle":"20°","vce_sat":"0.4V","power_dissipation":"0.1W","dark_current":"100nA","operating_temp":"-40℃~85℃"}', '0.12', '', 'https://picsum.photos/seed/OKLPT3MMNPN/300/300', '', 1),
('phototransistor', 'default', 'OKL-PT-5MM-NPN', 'OKAYLIGHT', '{"package_spec":"5mm","transistor_type":"NPN","peak_wavelength":"940nm","vceo":"30V","collector_current":"20mA","viewing_angle":"30°","vce_sat":"0.4V","power_dissipation":"0.1W","dark_current":"100nA","operating_temp":"-40℃~85℃"}', '0.15', '', 'https://picsum.photos/seed/OKLPT5MMNPN/300/300', '', 2),
('phototransistor', 'default', 'OKL-PT-0603-NPN', 'OKAYLIGHT', '{"package_spec":"0603","transistor_type":"NPN","peak_wavelength":"940nm","vceo":"30V","collector_current":"20mA","viewing_angle":"40°","vce_sat":"0.4V","power_dissipation":"0.075W","dark_current":"100nA","operating_temp":"-40℃~85℃"}', '0.10', '', 'https://picsum.photos/seed/OKLPT0603NPN/300/300', '', 3),
('phototransistor', 'default', 'OKL-PT-1206-DAR', 'OKAYLIGHT', '{"package_spec":"1206","transistor_type":"达林顿","peak_wavelength":"940nm","vceo":"50V","collector_current":"50mA","viewing_angle":"30°","vce_sat":"1.0V","power_dissipation":"0.15W","dark_current":"100nA","operating_temp":"-40℃~85℃"}', '0.22', '', 'https://picsum.photos/seed/OKLPT1206DAR/300/300', '', 4);

-- 6.6 红外遥控接收头(IRM) 产品
INSERT INTO products (category, kind, model, manufacturer, spec_data, price, datasheet_url, image_url, remarks, sort_order) VALUES
('irm', 'default', 'OKL-IRM-1838', 'OKAYLIGHT', '{"package_spec":"IRM-1838","receive_distance":"18m","center_frequency":"38kHz","receive_angle":"±45°","working_voltage":"2.7-5.5V","working_current":"0.8mA","power_dissipation":"0.05W","operating_temp":"-25℃~85℃"}', '0.25', '', 'https://picsum.photos/seed/OKLIRM1838/300/300', '', 1),
('irm', 'default', 'OKL-IRM-3638', 'OKAYLIGHT', '{"package_spec":"IRM-3638","receive_distance":"20m","center_frequency":"38kHz","receive_angle":"±45°","working_voltage":"2.7-5.5V","working_current":"0.8mA","power_dissipation":"0.05W","operating_temp":"-25℃~85℃"}', '0.28', '', 'https://picsum.photos/seed/OKLIRM3638/300/300', '', 2),
('irm', 'default', 'OKL-IRM-5638', 'OKAYLIGHT', '{"package_spec":"IRM-5638","receive_distance":"15m","center_frequency":"38kHz","receive_angle":"±45°","working_voltage":"2.7-5.5V","working_current":"0.8mA","power_dissipation":"0.05W","operating_temp":"-25℃~85℃"}', '0.26', '', 'https://picsum.photos/seed/OKLIRM5638/300/300', '', 3),
('irm', 'default', 'OKL-IRM-0038', 'OKAYLIGHT', '{"package_spec":"IRM-0038","receive_distance":"10m","center_frequency":"38kHz","receive_angle":"±35°","working_voltage":"2.7-5.5V","working_current":"0.5mA","power_dissipation":"0.03W","operating_temp":"-25℃~85℃"}', '0.18', '', 'https://picsum.photos/seed/OKLIRM0038/300/300', '', 4),
('irm', 'default', 'OKL-IRM-3838-SMD', 'OKAYLIGHT', '{"package_spec":"IRM-3838-SMD","receive_distance":"15m","center_frequency":"38kHz","receive_angle":"±45°","working_voltage":"2.7-5.5V","working_current":"0.6mA","power_dissipation":"0.04W","operating_temp":"-25℃~85℃"}', '0.32', '', 'https://picsum.photos/seed/OKLIRM3838SMD/300/300', '', 5);

-- 6.7 光电二极管 产品
INSERT INTO products (category, kind, model, manufacturer, spec_data, price, datasheet_url, image_url, remarks, sort_order) VALUES
('photodiode', 'default', 'OKL-PD-5MM-940', 'OKAYLIGHT', '{"package_spec":"5mm","peak_wavelength":"940nm","spectral_range":"400-1100nm","receive_angle":"30°","reverse_voltage":"30V","power_dissipation":"0.1W","dark_current":"30nA","operating_temp":"-40℃~85℃"}', '0.18', '', 'https://picsum.photos/seed/OKLPD5MM940/300/300', '', 1),
('photodiode', 'default', 'OKL-PD-3MM-940', 'OKAYLIGHT', '{"package_spec":"3mm","peak_wavelength":"940nm","spectral_range":"400-1100nm","receive_angle":"20°","reverse_voltage":"30V","power_dissipation":"0.1W","dark_current":"30nA","operating_temp":"-40℃~85℃"}', '0.15', '', 'https://picsum.photos/seed/OKLPD3MM940/300/300', '', 2),
('photodiode', 'default', 'OKL-PD-0603-940', 'OKAYLIGHT', '{"package_spec":"0603","peak_wavelength":"940nm","spectral_range":"400-1100nm","receive_angle":"40°","reverse_voltage":"30V","power_dissipation":"0.075W","dark_current":"30nA","operating_temp":"-40℃~85℃"}', '0.12', '', 'https://picsum.photos/seed/OKLPD0603940/300/300', '', 3),
('photodiode', 'default', 'OKL-PD-1206-850', 'OKAYLIGHT', '{"package_spec":"1206","peak_wavelength":"850nm","spectral_range":"400-1100nm","receive_angle":"30°","reverse_voltage":"30V","power_dissipation":"0.1W","dark_current":"30nA","operating_temp":"-40℃~85℃"}', '0.15', '', 'https://picsum.photos/seed/OKLPD1206850/300/300', '', 4);

-- 6.8 激光二极管 产品
INSERT INTO products (category, kind, model, manufacturer, spec_data, price, datasheet_url, image_url, remarks, sort_order) VALUES
('laser_diode', 'default', 'OKL-LD-650-5MW', 'OKAYLIGHT', '{"package_spec":"TO-18","dominant_wavelength":"650nm","conversion_efficiency":"25%","threshold_current":"35mA","esd_rating":"HBM 500V","working_voltage":"2.2V","working_current":"40mA","emission_color":"红光","horizontal_divergence":"8°","vertical_divergence":"30°","output_power":"5mW","slope_efficiency":"0.3mW/mA","operating_temp":"-10℃~60℃"}', '0.85', '', 'https://picsum.photos/seed/OKLLD6505MW/300/300', '', 1),
('laser_diode', 'default', 'OKL-LD-445-1W', 'OKAYLIGHT', '{"package_spec":"TO-56","dominant_wavelength":"445nm","conversion_efficiency":"30%","threshold_current":"120mA","esd_rating":"HBM 500V","working_voltage":"4.5V","working_current":"350mA","emission_color":"蓝光","horizontal_divergence":"8°","vertical_divergence":"30°","output_power":"1000mW","slope_efficiency":"1.0mW/mA","operating_temp":"-10℃~60℃"}', '5.85', '', 'https://picsum.photos/seed/OKLLD4451W/300/300', '', 2),
('laser_diode', 'default', 'OKL-LD-808-200MW', 'OKAYLIGHT', '{"package_spec":"TO-18","dominant_wavelength":"808nm","conversion_efficiency":"40%","threshold_current":"60mA","esd_rating":"HBM 500V","working_voltage":"1.8V","working_current":"250mA","emission_color":"红外","horizontal_divergence":"8°","vertical_divergence":"30°","output_power":"200mW","slope_efficiency":"0.6mW/mA","operating_temp":"-10℃~60℃"}', '2.45', '', 'https://picsum.photos/seed/OKLLD808200MW/300/300', '', 3),
('laser_diode', 'default', 'OKL-LD-520-50MW', 'OKAYLIGHT', '{"package_spec":"TO-56","dominant_wavelength":"520nm","conversion_efficiency":"28%","threshold_current":"70mA","esd_rating":"HBM 500V","working_voltage":"2.2V","working_current":"140mA","emission_color":"绿光","horizontal_divergence":"8°","vertical_divergence":"30°","output_power":"50mW","slope_efficiency":"0.5mW/mA","operating_temp":"-10℃~60℃"}', '3.25', '', 'https://picsum.photos/seed/OKLLD52050MW/300/300', '', 4),
('laser_diode', 'default', 'OKL-LD-650-1MW-3P', 'OKAYLIGHT', '{"package_spec":"3.3mm","dominant_wavelength":"650nm","conversion_efficiency":"20%","threshold_current":"25mA","esd_rating":"HBM 500V","working_voltage":"2.2V","working_current":"30mA","emission_color":"红光","horizontal_divergence":"6°","vertical_divergence":"35°","output_power":"1mW","slope_efficiency":"0.2mW/mA","operating_temp":"-10℃~60℃"}', '0.45', '', 'https://picsum.photos/seed/OKLLD6501MW3P/300/300', '', 5);

-- 6.9 RGB LED 产品
INSERT INTO products (category, kind, model, manufacturer, spec_data, price, datasheet_url, image_url, remarks, sort_order) VALUES
('rgb_led', 'default', 'OKL-RGB-5050', 'OKAYLIGHT', '{"package_spec":"5050","diode_config":"3芯片共阳","esd_rating":"HBM 2000V","viewing_angle":"120°","dominant_wavelength_g":"525nm","dominant_wavelength_b":"470nm","dominant_wavelength_r":"620nm","base_type":"贴片","lens_color":"乳白","tape_type":"编带","peak_wavelength_g":"515nm","peak_wavelength_b":"465nm","peak_wavelength_r":"625nm","luminous_intensity_g":"3000mcd","luminous_intensity_b":"2500mcd","luminous_intensity_r":"2000mcd","forward_voltage_g":"3.2V","forward_voltage_b":"3.2V","forward_voltage_r":"2.0V","forward_current_g":"20mA","forward_current_b":"20mA","forward_current_r":"20mA","power_r":"0.04W","power_g":"0.064W","power_b":"0.064W","operating_temp":"-40℃~85℃"}', '0.18', '', 'https://picsum.photos/seed/OKLRGB5050/300/300', '', 1),
('rgb_led', 'default', 'OKL-RGB-3528', 'OKAYLIGHT', '{"package_spec":"3528","diode_config":"3芯片共阴","esd_rating":"HBM 2000V","viewing_angle":"120°","dominant_wavelength_g":"525nm","dominant_wavelength_b":"470nm","dominant_wavelength_r":"620nm","base_type":"贴片","lens_color":"乳白","tape_type":"编带","peak_wavelength_g":"515nm","peak_wavelength_b":"465nm","peak_wavelength_r":"625nm","luminous_intensity_g":"2000mcd","luminous_intensity_b":"1800mcd","luminous_intensity_r":"1500mcd","forward_voltage_g":"3.0V","forward_voltage_b":"3.0V","forward_voltage_r":"2.0V","forward_current_g":"20mA","forward_current_b":"20mA","forward_current_r":"20mA","power_r":"0.04W","power_g":"0.06W","power_b":"0.06W","operating_temp":"-40℃~85℃"}', '0.12', '', 'https://picsum.photos/seed/OKLRGB3528/300/300', '', 2),
('rgb_led', 'default', 'OKL-RGB-5050-CA', 'OKAYLIGHT', '{"package_spec":"5050","diode_config":"3芯片共阳","esd_rating":"HBM 2000V","viewing_angle":"120°","dominant_wavelength_g":"530nm","dominant_wavelength_b":"460nm","dominant_wavelength_r":"625nm","base_type":"贴片","lens_color":"透明","tape_type":"编带","peak_wavelength_g":"520nm","peak_wavelength_b":"455nm","peak_wavelength_r":"630nm","luminous_intensity_g":"3500mcd","luminous_intensity_b":"2800mcd","luminous_intensity_r":"2500mcd","forward_voltage_g":"3.2V","forward_voltage_b":"3.2V","forward_voltage_r":"2.0V","forward_current_g":"20mA","forward_current_b":"20mA","forward_current_r":"20mA","power_r":"0.04W","power_g":"0.064W","power_b":"0.064W","operating_temp":"-40℃~85℃"}', '0.20', '', 'https://picsum.photos/seed/OKLRGB5050CA/300/300', '', 3),
('rgb_led', 'default', 'OKL-RGB-1206', 'OKAYLIGHT', '{"package_spec":"1206","diode_config":"3芯片共阴","esd_rating":"HBM 2000V","viewing_angle":"120°","dominant_wavelength_g":"525nm","dominant_wavelength_b":"470nm","dominant_wavelength_r":"620nm","base_type":"贴片","lens_color":"乳白","tape_type":"编带","peak_wavelength_g":"515nm","peak_wavelength_b":"465nm","peak_wavelength_r":"625nm","luminous_intensity_g":"1500mcd","luminous_intensity_b":"1200mcd","luminous_intensity_r":"1000mcd","forward_voltage_g":"3.0V","forward_voltage_b":"3.0V","forward_voltage_r":"2.0V","forward_current_g":"20mA","forward_current_b":"20mA","forward_current_r":"20mA","power_r":"0.04W","power_g":"0.06W","power_b":"0.06W","operating_temp":"-40℃~85℃"}', '0.10', '', 'https://picsum.photos/seed/OKLRGB1206/300/300', '', 4),
('rgb_led', 'default', 'OKL-RGB-5MM-DIP', 'OKAYLIGHT', '{"package_spec":"5mm","diode_config":"3芯片共阴","esd_rating":"HBM 2000V","viewing_angle":"30°","dominant_wavelength_g":"525nm","dominant_wavelength_b":"470nm","dominant_wavelength_r":"620nm","base_type":"直插","lens_color":"乳白","tape_type":"盒装","peak_wavelength_g":"515nm","peak_wavelength_b":"465nm","peak_wavelength_r":"625nm","luminous_intensity_g":"4000mcd","luminous_intensity_b":"3000mcd","luminous_intensity_r":"2500mcd","forward_voltage_g":"3.2V","forward_voltage_b":"3.2V","forward_voltage_r":"2.0V","forward_current_g":"20mA","forward_current_b":"20mA","forward_current_r":"20mA","power_r":"0.04W","power_g":"0.064W","power_b":"0.064W","operating_temp":"-40℃~85℃"}', '0.15', '', 'https://picsum.photos/seed/OKLRGB5MMDIP/300/300', '', 5);

-- 6.10 RGB LED(内置IC) 产品
INSERT INTO products (category, kind, model, manufacturer, spec_data, price, datasheet_url, image_url, remarks, sort_order) VALUES
('rgb_led_ic', 'default', 'OKL-WS2812-5050', 'OKAYLIGHT', '{"package_spec":"5050","esd_rating":"HBM 2000V","viewing_angle":"120°","working_voltage":"3.3-5V","static_current":"0.6mA","pwm_frequency":"400Hz","data_rate":"800Kbps","dominant_wavelength_g":"525nm","dominant_wavelength_b":"470nm","dominant_wavelength_r":"620nm","base_type":"贴片","lens_color":"乳白","tape_type":"编带","peak_wavelength_g":"515nm","peak_wavelength_b":"465nm","peak_wavelength_r":"625nm","luminous_intensity_g":"3000mcd","luminous_intensity_b":"2500mcd","luminous_intensity_r":"2000mcd","propagation_delay":"300ns","rise_time":"300ns","fall_time":"300ns","operating_temp":"-40℃~85℃"}', '0.25', '', 'https://picsum.photos/seed/OKLWS28125050/300/300', '', 1),
('rgb_led_ic', 'default', 'OKL-SK6812-5050', 'OKAYLIGHT', '{"package_spec":"5050","esd_rating":"HBM 2000V","viewing_angle":"120°","working_voltage":"3.3-5V","static_current":"0.6mA","pwm_frequency":"1.2kHz","data_rate":"800Kbps","dominant_wavelength_g":"525nm","dominant_wavelength_b":"470nm","dominant_wavelength_r":"620nm","base_type":"贴片","lens_color":"乳白","tape_type":"编带","peak_wavelength_g":"515nm","peak_wavelength_b":"465nm","peak_wavelength_r":"625nm","luminous_intensity_g":"3500mcd","luminous_intensity_b":"2800mcd","luminous_intensity_r":"2200mcd","propagation_delay":"300ns","rise_time":"300ns","fall_time":"300ns","operating_temp":"-40℃~85℃"}', '0.28', '', 'https://picsum.photos/seed/OKLSK68125050/300/300', '', 2),
('rgb_led_ic', 'default', 'OKL-WS2812-3528', 'OKAYLIGHT', '{"package_spec":"3528","esd_rating":"HBM 2000V","viewing_angle":"120°","working_voltage":"3.3-5V","static_current":"0.4mA","pwm_frequency":"400Hz","data_rate":"800Kbps","dominant_wavelength_g":"525nm","dominant_wavelength_b":"470nm","dominant_wavelength_r":"620nm","base_type":"贴片","lens_color":"乳白","tape_type":"编带","peak_wavelength_g":"515nm","peak_wavelength_b":"465nm","peak_wavelength_r":"625nm","luminous_intensity_g":"2000mcd","luminous_intensity_b":"1800mcd","luminous_intensity_r":"1500mcd","propagation_delay":"300ns","rise_time":"300ns","fall_time":"300ns","operating_temp":"-40℃~85℃"}', '0.18', '', 'https://picsum.photos/seed/OKLWS28123528/300/300', '', 3),
('rgb_led_ic', 'default', 'OKL-WS2811-5050-RGBW', 'OKAYLIGHT', '{"package_spec":"5050","esd_rating":"HBM 2000V","viewing_angle":"120°","working_voltage":"5V","static_current":"0.8mA","pwm_frequency":"400Hz","data_rate":"800Kbps","dominant_wavelength_g":"525nm","dominant_wavelength_b":"470nm","dominant_wavelength_r":"620nm","base_type":"贴片","lens_color":"乳白","tape_type":"编带","peak_wavelength_g":"515nm","peak_wavelength_b":"465nm","peak_wavelength_r":"625nm","luminous_intensity_g":"3500mcd","luminous_intensity_b":"3000mcd","luminous_intensity_r":"2500mcd","propagation_delay":"300ns","rise_time":"300ns","fall_time":"300ns","operating_temp":"-40℃~85℃"}', '0.32', '', 'https://picsum.photos/seed/OKLWS28115050RGBW/300/300', '', 4);


-- 6.11 槽型光电开关(光电晶体管输出) 产品
INSERT INTO products (category, kind, model, manufacturer, spec_data, price, datasheet_url, image_url, remarks, sort_order) VALUES
('slot_photo_switch', 'default', 'OKL-SLOT-2MM', 'OKAYLIGHT', '{"package_spec":"EE-SX1105","slot_width":"2mm","slit_width":"0.5mm","forward_voltage":"1.2V","peak_wavelength":"940nm","dark_current":"100nA","load_voltage":"30V","load_current":"20mA","rise_time":"4us","fall_time":"3us","pin_pitch":"2.54mm","operating_temp":"-25℃~85℃"}', '0.35', '', 'https://picsum.photos/seed/OKLSLOT2MM/300/300', '', 1),
('slot_photo_switch', 'default', 'OKL-SLOT-3MM', 'OKAYLIGHT', '{"package_spec":"EE-SX1106","slot_width":"3mm","slit_width":"0.5mm","forward_voltage":"1.2V","peak_wavelength":"940nm","dark_current":"100nA","load_voltage":"30V","load_current":"20mA","rise_time":"4us","fall_time":"3us","pin_pitch":"2.54mm","operating_temp":"-25℃~85℃"}', '0.38', '', 'https://picsum.photos/seed/OKLSLOT3MM/300/300', '', 2),
('slot_photo_switch', 'default', 'OKL-SLOT-5MM', 'OKAYLIGHT', '{"package_spec":"EE-SX1107","slot_width":"5mm","slit_width":"1.0mm","forward_voltage":"1.2V","peak_wavelength":"940nm","dark_current":"100nA","load_voltage":"30V","load_current":"20mA","rise_time":"5us","fall_time":"4us","pin_pitch":"5.0mm","operating_temp":"-25℃~85℃"}', '0.42', '', 'https://picsum.photos/seed/OKLSLOT5MM/300/300', '', 3),
('slot_photo_switch', 'default', 'OKL-SLOT-5MM-SMD', 'OKAYLIGHT', '{"package_spec":"EE-SX4601","slot_width":"5mm","slit_width":"0.8mm","forward_voltage":"1.2V","peak_wavelength":"940nm","dark_current":"100nA","load_voltage":"30V","load_current":"20mA","rise_time":"3us","fall_time":"2us","pin_pitch":"2.54mm","operating_temp":"-25℃~85℃"}', '0.48', '', 'https://picsum.photos/seed/OKLSLOT5MMSMD/300/300', '', 4);

-- 6.12 反射式光电开关 产品
INSERT INTO products (category, kind, model, manufacturer, spec_data, price, datasheet_url, image_url, remarks, sort_order) VALUES
('reflective_photo_switch', 'default', 'OKL-RFL-2MM', 'OKAYLIGHT', '{"package_spec":"EE-1004","sensing_distance":"2mm","receiver_type":"光电晶体管","collector_current":"20mA","vceo":"30V","vce_sat":"0.4V","wavelength":"940nm","forward_voltage":"1.2V","forward_current":"20mA","reverse_voltage":"5V","rise_time":"5us","fall_time":"5us","power_dissipation":"0.1W","operating_temp":"-25℃~85℃"}', '0.32', '', 'https://picsum.photos/seed/OKLRFL2MM/300/300', '', 1),
('reflective_photo_switch', 'default', 'OKL-RFL-5MM', 'OKAYLIGHT', '{"package_spec":"EE-1005","sensing_distance":"5mm","receiver_type":"光电晶体管","collector_current":"20mA","vceo":"30V","vce_sat":"0.4V","wavelength":"940nm","forward_voltage":"1.2V","forward_current":"20mA","reverse_voltage":"5V","rise_time":"8us","fall_time":"8us","power_dissipation":"0.1W","operating_temp":"-25℃~85℃"}', '0.38', '', 'https://picsum.photos/seed/OKLRFL5MM/300/300', '', 2),
('reflective_photo_switch', 'default', 'OKL-RFL-10MM', 'OKAYLIGHT', '{"package_spec":"EE-1006","sensing_distance":"10mm","receiver_type":"光电达林顿","collector_current":"50mA","vceo":"50V","vce_sat":"1.0V","wavelength":"940nm","forward_voltage":"1.2V","forward_current":"20mA","reverse_voltage":"5V","rise_time":"15us","fall_time":"15us","power_dissipation":"0.15W","operating_temp":"-25℃~85℃"}', '0.45', '', 'https://picsum.photos/seed/OKLRFL10MM/300/300', '', 3),
('reflective_photo_switch', 'default', 'OKL-RFL-3MM-SMD', 'OKAYLIGHT', '{"package_spec":"EE-SX4602","sensing_distance":"3mm","receiver_type":"光电晶体管","collector_current":"20mA","vceo":"30V","vce_sat":"0.4V","wavelength":"940nm","forward_voltage":"1.2V","forward_current":"20mA","reverse_voltage":"5V","rise_time":"4us","fall_time":"4us","power_dissipation":"0.1W","operating_temp":"-25℃~85℃"}', '0.35', '', 'https://picsum.photos/seed/OKLRFL3MMSMD/300/300', '', 4);

-- 6.13 LED驱动 产品
INSERT INTO products (category, kind, model, manufacturer, spec_data, price, datasheet_url, image_url, remarks, sort_order) VALUES
('led_driver', 'default', 'OKL-DRV-PT4115', 'OKAYLIGHT', '{"package_spec":"SOT89-5","driver_type":"降压型","topology":"Buck","channel_count":"1","working_voltage_dc":"6-30V","working_voltage_ac":"-","switching_frequency":"500kHz","switch_type":"内置","output_voltage":"3-28V","output_current":"1.2A","current_accuracy":"±3%","dimming":"PWM","features":"过温保护/过流保护","operating_temp":"-40℃~125℃"}', '0.35', '', 'https://picsum.photos/seed/OKLDRVPT4115/300/300', '', 1),
('led_driver', 'default', 'OKL-DRV-AMC7150', 'OKAYLIGHT', '{"package_spec":"TO-252","driver_type":"降压型","topology":"Buck","channel_count":"1","working_voltage_dc":"4-40V","working_voltage_ac":"-","switching_frequency":"200kHz","switch_type":"内置","output_voltage":"3-38V","output_current":"1.5A","current_accuracy":"±5%","dimming":"PWM","features":"过温保护","operating_temp":"-40℃~125℃"}', '0.28', '', 'https://picsum.photos/seed/OKLDRVAMC7150/300/300', '', 2),
('led_driver', 'default', 'OKL-DRV-LM3409', 'OKAYLIGHT', '{"package_spec":"TSSOP-14","driver_type":"降压型","topology":"Buck","channel_count":"1","working_voltage_dc":"6-42V","working_voltage_ac":"-","switching_frequency":"1MHz","switch_type":"外置","output_voltage":"5-40V","output_current":"5A","current_accuracy":"±2%","dimming":"PWM/模拟","features":"过流保护/过温保护/EN使能","operating_temp":"-40℃~125℃"}', '0.85', '', 'https://picsum.photos/seed/OKLDRVLM3409/300/300', '', 3),
('led_driver', 'default', 'OKL-DRV-PT4101', 'OKAYLIGHT', '{"package_spec":"SOT23-6","driver_type":"升压型","topology":"Boost","channel_count":"1","working_voltage_dc":"2.5-5.5V","working_voltage_ac":"-","switching_frequency":"1.2MHz","switch_type":"内置","output_voltage":"3-26V","output_current":"0.5A","current_accuracy":"±3%","dimming":"PWM","features":"过流保护/欠压保护","operating_temp":"-40℃~85℃"}', '0.22', '', 'https://picsum.photos/seed/OKLDRVPT4101/300/300', '', 4),
('led_driver', 'default', 'OKL-DRV-WS2811', 'OKAYLIGHT', '{"package_spec":"SOP-8","driver_type":"恒流型","topology":"线性","channel_count":"3","working_voltage_dc":"6-7V","working_voltage_ac":"-","switching_frequency":"400Hz","switch_type":"内置","output_voltage":"3-6V","output_current":"18.5mA","current_accuracy":"±1%","dimming":"PWM","features":"内置振荡器/级联输出","operating_temp":"-40℃~85℃"}', '0.15', '', 'https://picsum.photos/seed/OKLDRVWS2811/300/300', '', 5);

-- 6.14 LED数码管 产品
INSERT INTO products (category, kind, model, manufacturer, spec_data, price, datasheet_url, image_url, remarks, sort_order) VALUES
('led_display', 'default', 'OKL-DSP-1DIG-056-RED', 'OKAYLIGHT', '{"package_spec":"0.56寸-1位","digit_count":"1","char_size":"0.56","display_type":"共阴","led_polarity":"共阴","emission_color":"红光","luminous_intensity":"3000mcd","power_dissipation":"0.4W","forward_voltage":"2.0V","operating_temp":"-40℃~85℃"}', '0.18', '', 'https://picsum.photos/seed/OKLDSP1DIG056RED/300/300', '', 1),
('led_display', 'default', 'OKL-DSP-1DIG-056-GRN', 'OKAYLIGHT', '{"package_spec":"0.56寸-1位","digit_count":"1","char_size":"0.56","display_type":"共阳","led_polarity":"共阳","emission_color":"绿光","luminous_intensity":"5000mcd","power_dissipation":"0.4W","forward_voltage":"2.2V","operating_temp":"-40℃~85℃"}', '0.20', '', 'https://picsum.photos/seed/OKLDSP1DIG056GRN/300/300', '', 2),
('led_display', 'default', 'OKL-DSP-4DIG-056-RED', 'OKAYLIGHT', '{"package_spec":"0.56寸-4位","digit_count":"4","char_size":"0.56","display_type":"共阴","led_polarity":"共阴","emission_color":"红光","luminous_intensity":"2500mcd","power_dissipation":"1.2W","forward_voltage":"2.0V","operating_temp":"-40℃~85℃"}', '0.55', '', 'https://picsum.photos/seed/OKLDSP4DIG056RED/300/300', '', 3),
('led_display', 'default', 'OKL-DSP-2DIG-036-BLU', 'OKAYLIGHT', '{"package_spec":"0.36寸-2位","digit_count":"2","char_size":"0.36","display_type":"共阳","led_polarity":"共阳","emission_color":"蓝光","luminous_intensity":"2000mcd","power_dissipation":"0.3W","forward_voltage":"3.2V","operating_temp":"-40℃~85℃"}', '0.28', '', 'https://picsum.photos/seed/OKLDSP2DIG036BLU/300/300', '', 4),
('led_display', 'default', 'OKL-DSP-4DIG-036-WHT', 'OKAYLIGHT', '{"package_spec":"0.36寸-4位","digit_count":"4","char_size":"0.36","display_type":"共阴","led_polarity":"共阴","emission_color":"白光","luminous_intensity":"3000mcd","power_dissipation":"0.8W","forward_voltage":"3.0V","operating_temp":"-40℃~85℃"}', '0.48', '', 'https://picsum.photos/seed/OKLDSP4DIG036WHT/300/300', '', 5);

-- 6.15 LED保护 产品
INSERT INTO products (category, kind, model, manufacturer, spec_data, price, datasheet_url, image_url, remarks, sort_order) VALUES
('led_protection', 'default', 'OKL-PRO-6V-SMD', 'OKAYLIGHT', '{"package_spec":"SOD-323","trigger_voltage":"6V","leakage_current":"1uA","hold_current":"50mA","on_state_voltage":"1.5V","on_state_current":"200mA","features":"自恢复保险丝","operating_temp":"-40℃~85℃"}', '0.08', '', 'https://picsum.photos/seed/OKLPRO6VSMD/300/300', '', 1),
('led_protection', 'default', 'OKL-PRO-9V-SMD', 'OKAYLIGHT', '{"package_spec":"SOD-323","trigger_voltage":"9V","leakage_current":"1uA","hold_current":"100mA","on_state_voltage":"1.5V","on_state_current":"300mA","features":"自恢复保险丝","operating_temp":"-40℃~85℃"}', '0.10', '', 'https://picsum.photos/seed/OKLPRO9VSMD/300/300', '', 2),
('led_protection', 'default', 'OKL-PRO-12V-DIP', 'OKAYLIGHT', '{"package_spec":"DIP","trigger_voltage":"12V","leakage_current":"2uA","hold_current":"150mA","on_state_voltage":"2.0V","on_state_current":"500mA","features":"自恢复保险丝/过压保护","operating_temp":"-40℃~85℃"}', '0.15', '', 'https://picsum.photos/seed/OKLPRO12VDIP/300/300', '', 3),
('led_protection', 'default', 'OKL-PRO-24V-SMD', 'OKAYLIGHT', '{"package_spec":"SOD-123","trigger_voltage":"24V","leakage_current":"2uA","hold_current":"200mA","on_state_voltage":"2.5V","on_state_current":"800mA","features":"自恢复保险丝/过压保护","operating_temp":"-40℃~85℃"}', '0.18', '', 'https://picsum.photos/seed/OKLPRO24VSMD/300/300', '', 4);

-- 6.16 静电和浪涌保护(TVS/ESD) 产品
INSERT INTO products (category, kind, model, manufacturer, spec_data, price, datasheet_url, image_url, remarks, sort_order) VALUES
('tvs_esd', 'default', 'OKL-TVS-3V3-SOD323', 'OKAYLIGHT', '{"package_spec":"SOD-323","device_type":"TVS","channel_count":"1","polarity":"单向","vrwm":"3.3V","vbr":"4.0V","reverse_current":"1uA","ipp":"10A","clamp_voltage":"5.5V","ppp":"150W","cj":"50pF","protection_level":"IEC61000-4-2 ±15kV","operating_temp":"-55℃~150℃"}', '0.06', '', 'https://picsum.photos/seed/OKLTVS3V3SOD323/300/300', '', 1),
('tvs_esd', 'default', 'OKL-TVS-5V-SOD323', 'OKAYLIGHT', '{"package_spec":"SOD-323","device_type":"TVS","channel_count":"1","polarity":"单向","vrwm":"5V","vbr":"6.0V","reverse_current":"1uA","ipp":"12A","clamp_voltage":"8.0V","ppp":"200W","cj":"40pF","protection_level":"IEC61000-4-2 ±15kV","operating_temp":"-55℃~150℃"}', '0.06', '', 'https://picsum.photos/seed/OKLTVS5VSOD323/300/300', '', 2),
('tvs_esd', 'default', 'OKL-TVS-12V-SMA', 'OKAYLIGHT', '{"package_spec":"SMA","device_type":"TVS","channel_count":"1","polarity":"单向","vrwm":"12V","vbr":"13.3V","reverse_current":"1uA","ipp":"16A","clamp_voltage":"19.9V","ppp":"400W","cj":"150pF","protection_level":"IEC61000-4-2 ±30kV","operating_temp":"-55℃~150℃"}', '0.12', '', 'https://picsum.photos/seed/OKLTVS12VSMA/300/300', '', 3),
('tvs_esd', 'default', 'OKL-ESD-5V-SOT23', 'OKAYLIGHT', '{"package_spec":"SOT-23","device_type":"ESD","channel_count":"2","polarity":"双向","vrwm":"5V","vbr":"6.0V","reverse_current":"0.5uA","ipp":"5A","clamp_voltage":"9.8V","ppp":"50W","cj":"5pF","protection_level":"IEC61000-4-2 ±8kV","operating_temp":"-55℃~150℃"}', '0.04', '', 'https://picsum.photos/seed/OKLESD5VSOT23/300/300', '', 4),
('tvs_esd', 'default', 'OKL-ESD-12V-DFN', 'OKAYLIGHT', '{"package_spec":"DFN-2x2","device_type":"ESD","channel_count":"4","polarity":"双向","vrwm":"12V","vbr":"14V","reverse_current":"1uA","ipp":"6A","clamp_voltage":"22V","ppp":"80W","cj":"8pF","protection_level":"IEC61000-4-2 ±15kV","operating_temp":"-55℃~150℃"}', '0.08', '', 'https://picsum.photos/seed/OKLESD12VDFN/300/300', '', 5);

-- ============================================================
-- 初始化完成
-- ============================================================
